# Generated by Django 5.1.1 on 2024-09-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desempenho',
            name='economia_final',
            field=models.FloatField(verbose_name='Economia final'),
        ),
    ]
