# Generated by Django 5.1.1 on 2024-09-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_desempenho_economia_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desempenho',
            name='popularidade_final',
            field=models.IntegerField(verbose_name='Popularidade final'),
        ),
    ]
