# Generated by Django 5.1.1 on 2024-09-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_desempenho_popularidade_final'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuracao',
        ),
    ]
